"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var log_1 = require("../../../log");
var regions_1 = require("../../../regions");
var vector3_1 = require("../../../vector3");
var Location = Java.type('org.bukkit.Location');
var log = log_1.Logger(__filename);
exports.getLocations = function (bukkitWorld) {
    return {
        world: bukkitWorld,
        waypoints: {
            arenaThreshold: {
                region: [
                    new Location(bukkitWorld, 3, 66, -54),
                    new Location(bukkitWorld, -3, 68, -31),
                ],
                saveLocation: new Location(bukkitWorld, -1, 66, -29, 1, 12),
            },
        },
        locations: {
            spawn: new Location(bukkitWorld, -18, 101, -67, -32, 0),
            // spawn: new Location(world, -1, 66, -29, 1, 12),
            magmabossSpawn: new Location(bukkitWorld, 0, 63, 0),
            endChest: new Location(bukkitWorld, 6, 71, 90),
            dispensers: [
                new Location(bukkitWorld, -23, 61, -28),
                new Location(bukkitWorld, -19, 61, -28),
                new Location(bukkitWorld, -8, 61, -28),
                new Location(bukkitWorld, 5, 61, -28),
                new Location(bukkitWorld, 13, 61, -28),
                new Location(bukkitWorld, 19, 61, -28),
                new Location(bukkitWorld, 28, 61, -28),
                new Location(bukkitWorld, 25, 61, -27),
                new Location(bukkitWorld, -27, 61, -26),
                new Location(bukkitWorld, -15, 61, -26),
                new Location(bukkitWorld, -12, 61, -26),
                new Location(bukkitWorld, -3, 61, -26),
                new Location(bukkitWorld, 2, 61, -26),
                new Location(bukkitWorld, 7, 61, -26),
                new Location(bukkitWorld, 10, 61, -26),
                new Location(bukkitWorld, 17, 61, -26),
                new Location(bukkitWorld, 21, 61, -26),
                new Location(bukkitWorld, -21, 61, -25),
                new Location(bukkitWorld, 16, 61, -25),
                new Location(bukkitWorld, -16, 61, -23),
                new Location(bukkitWorld, -8, 61, -23),
                new Location(bukkitWorld, 0, 61, -23),
                new Location(bukkitWorld, 3, 61, -23),
                new Location(bukkitWorld, 9, 61, -23),
                new Location(bukkitWorld, 13, 61, -23),
                new Location(bukkitWorld, 21, 61, -23),
                new Location(bukkitWorld, 28, 61, -23),
                new Location(bukkitWorld, -12, 61, -22),
                new Location(bukkitWorld, -4, 61, -22),
                new Location(bukkitWorld, 18, 61, -22),
                new Location(bukkitWorld, 25, 61, -22),
                new Location(bukkitWorld, -28, 61, -21),
                new Location(bukkitWorld, -25, 61, -21),
                new Location(bukkitWorld, -22, 61, -21),
                new Location(bukkitWorld, -19, 61, -21),
                new Location(bukkitWorld, -6, 61, -20),
                new Location(bukkitWorld, 0, 61, -20),
                new Location(bukkitWorld, 3, 61, -20),
                new Location(bukkitWorld, 6, 61, -20),
                new Location(bukkitWorld, 10, 61, -20),
                new Location(bukkitWorld, 16, 61, -20),
                new Location(bukkitWorld, 21, 61, -20),
                new Location(bukkitWorld, 28, 61, -19),
                new Location(bukkitWorld, -28, 61, -18),
                new Location(bukkitWorld, -25, 61, -18),
                new Location(bukkitWorld, -22, 61, -18),
                new Location(bukkitWorld, -14, 61, -18),
                new Location(bukkitWorld, -11, 61, -18),
                new Location(bukkitWorld, -8, 61, -18),
                new Location(bukkitWorld, 10, 61, -17),
                new Location(bukkitWorld, 13, 61, -17),
                new Location(bukkitWorld, 21, 61, -17),
                new Location(bukkitWorld, 26, 61, -17),
                new Location(bukkitWorld, -6, 61, -16),
                new Location(bukkitWorld, 0, 61, -16),
                new Location(bukkitWorld, 6, 61, -16),
                new Location(bukkitWorld, 14, 61, -16),
                new Location(bukkitWorld, -22, 61, -15),
                new Location(bukkitWorld, -10, 61, -15),
                new Location(bukkitWorld, -28, 61, -14),
                new Location(bukkitWorld, -15, 61, -14),
                new Location(bukkitWorld, 17, 61, -14),
                new Location(bukkitWorld, 21, 61, -14),
                new Location(bukkitWorld, 24, 61, -14),
                new Location(bukkitWorld, 0, 61, -13),
                new Location(bukkitWorld, 3, 61, -13),
                new Location(bukkitWorld, 9, 61, -13),
                new Location(bukkitWorld, -25, 61, -12),
                new Location(bukkitWorld, -13, 61, -12),
                new Location(bukkitWorld, -8, 61, -12),
                new Location(bukkitWorld, -5, 61, -12),
                new Location(bukkitWorld, -2, 61, -12),
                new Location(bukkitWorld, 14, 61, -11),
                new Location(bukkitWorld, 19, 61, -11),
                new Location(bukkitWorld, 24, 61, -11),
                new Location(bukkitWorld, 27, 61, -11),
                new Location(bukkitWorld, -20, 61, -10),
                new Location(bukkitWorld, -15, 61, -10),
                new Location(bukkitWorld, -25, 61, -9),
                new Location(bukkitWorld, -13, 61, -9),
                new Location(bukkitWorld, 4, 61, -9),
                new Location(bukkitWorld, 8, 61, -9),
                new Location(bukkitWorld, 11, 61, -9),
                new Location(bukkitWorld, -28, 61, -8),
                new Location(bukkitWorld, -7, 61, -8),
                new Location(bukkitWorld, 24, 61, -8),
                new Location(bukkitWorld, 28, 61, -8),
                new Location(bukkitWorld, -22, 61, -6),
                new Location(bukkitWorld, -19, 61, -6),
                new Location(bukkitWorld, -16, 61, -6),
                new Location(bukkitWorld, -13, 61, -6),
                new Location(bukkitWorld, -10, 61, -6),
                new Location(bukkitWorld, -2, 61, -6),
                new Location(bukkitWorld, 1, 61, -6),
                new Location(bukkitWorld, 4, 61, -6),
                new Location(bukkitWorld, 13, 61, -6),
                new Location(bukkitWorld, 17, 61, -6),
                new Location(bukkitWorld, 20, 61, -6),
                new Location(bukkitWorld, 24, 61, -5),
                new Location(bukkitWorld, -25, 61, -3),
                new Location(bukkitWorld, -22, 61, -3),
                new Location(bukkitWorld, -13, 61, -3),
                new Location(bukkitWorld, -10, 61, -3),
                new Location(bukkitWorld, -7, 61, -3),
                new Location(bukkitWorld, 7, 61, -3),
                new Location(bukkitWorld, 10, 61, -3),
                new Location(bukkitWorld, 13, 61, -3),
                new Location(bukkitWorld, 17, 61, -3),
                new Location(bukkitWorld, 26, 61, -3),
                new Location(bukkitWorld, -27, 61, -2),
                new Location(bukkitWorld, 24, 61, -2),
                new Location(bukkitWorld, -22, 61, 0),
                new Location(bukkitWorld, -19, 61, 0),
                new Location(bukkitWorld, -16, 61, 0),
                new Location(bukkitWorld, -13, 61, 0),
                new Location(bukkitWorld, -10, 61, 0),
                new Location(bukkitWorld, 13, 61, 0),
                new Location(bukkitWorld, 17, 61, 0),
                new Location(bukkitWorld, 20, 61, 0),
                new Location(bukkitWorld, 26, 61, 0),
                new Location(bukkitWorld, -27, 61, 1),
                new Location(bukkitWorld, 23, 61, 1),
                new Location(bukkitWorld, 18, 61, 2),
                new Location(bukkitWorld, -25, 61, 3),
                new Location(bukkitWorld, -19, 61, 3),
                new Location(bukkitWorld, -16, 61, 3),
                new Location(bukkitWorld, -10, 61, 3),
                new Location(bukkitWorld, -7, 61, 3),
                new Location(bukkitWorld, 10, 61, 3),
                new Location(bukkitWorld, 26, 61, 3),
                new Location(bukkitWorld, -27, 61, 4),
                new Location(bukkitWorld, -19, 61, 6),
                new Location(bukkitWorld, -11, 61, 6),
                new Location(bukkitWorld, -7, 61, 6),
                new Location(bukkitWorld, 1, 61, 6),
                new Location(bukkitWorld, 4, 61, 6),
                new Location(bukkitWorld, 7, 61, 6),
                new Location(bukkitWorld, 10, 61, 6),
                new Location(bukkitWorld, 13, 61, 6),
                new Location(bukkitWorld, 17, 61, 6),
                new Location(bukkitWorld, 20, 61, 6),
                new Location(bukkitWorld, 26, 61, 6),
                new Location(bukkitWorld, -27, 61, 7),
                new Location(bukkitWorld, -21, 61, 7),
                new Location(bukkitWorld, 23, 61, 8),
                new Location(bukkitWorld, -25, 61, 9),
                new Location(bukkitWorld, -22, 61, 9),
                new Location(bukkitWorld, -14, 61, 9),
                new Location(bukkitWorld, -10, 61, 9),
                new Location(bukkitWorld, -7, 61, 9),
                new Location(bukkitWorld, -4, 61, 9),
                new Location(bukkitWorld, 10, 61, 9),
                new Location(bukkitWorld, 26, 61, 9),
                new Location(bukkitWorld, -27, 61, 10),
                new Location(bukkitWorld, 3, 61, 10),
                new Location(bukkitWorld, 13, 61, 10),
                new Location(bukkitWorld, 19, 61, 10),
                new Location(bukkitWorld, -12, 61, 11),
                new Location(bukkitWorld, -14, 61, 12),
                new Location(bukkitWorld, -5, 61, 12),
                new Location(bukkitWorld, -2, 61, 12),
                new Location(bukkitWorld, 1, 61, 12),
                new Location(bukkitWorld, 4, 61, 12),
                new Location(bukkitWorld, 8, 61, 12),
                new Location(bukkitWorld, 23, 61, 12),
                new Location(bukkitWorld, 26, 61, 12),
                new Location(bukkitWorld, -27, 61, 13),
                new Location(bukkitWorld, -21, 61, 13),
                new Location(bukkitWorld, -26, 61, 15),
                new Location(bukkitWorld, -5, 61, 15),
                new Location(bukkitWorld, -2, 61, 15),
                new Location(bukkitWorld, 7, 61, 15),
                new Location(bukkitWorld, 10, 61, 15),
                new Location(bukkitWorld, 13, 61, 15),
                new Location(bukkitWorld, 16, 61, 15),
                new Location(bukkitWorld, 19, 61, 15),
                new Location(bukkitWorld, 23, 61, 15),
                new Location(bukkitWorld, 26, 61, 15),
                new Location(bukkitWorld, 1, 61, 16),
                new Location(bukkitWorld, -24, 61, 17),
                new Location(bukkitWorld, -21, 61, 17),
                new Location(bukkitWorld, -14, 61, 17),
                new Location(bukkitWorld, -17, 61, 18),
                new Location(bukkitWorld, -18, 61, 18),
                new Location(bukkitWorld, 4, 61, 18),
                new Location(bukkitWorld, 13, 61, 18),
                new Location(bukkitWorld, 16, 61, 18),
                new Location(bukkitWorld, 23, 61, 18),
                new Location(bukkitWorld, 26, 61, 18),
                new Location(bukkitWorld, 20, 61, 19),
                new Location(bukkitWorld, -26, 61, 21),
                new Location(bukkitWorld, -17, 61, 21),
                new Location(bukkitWorld, -14, 61, 21),
                new Location(bukkitWorld, -11, 61, 21),
                new Location(bukkitWorld, -8, 61, 21),
                new Location(bukkitWorld, -5, 61, 21),
                new Location(bukkitWorld, -2, 61, 21),
                new Location(bukkitWorld, 1, 61, 21),
                new Location(bukkitWorld, 4, 61, 21),
                new Location(bukkitWorld, 7, 61, 21),
                new Location(bukkitWorld, 10, 61, 21),
                new Location(bukkitWorld, 13, 61, 21),
                new Location(bukkitWorld, 17, 61, 21),
                new Location(bukkitWorld, 26, 61, 21),
                new Location(bukkitWorld, -19, 61, 23),
                new Location(bukkitWorld, -26, 61, 24),
                new Location(bukkitWorld, -23, 61, 24),
                new Location(bukkitWorld, -16, 61, 24),
                new Location(bukkitWorld, -4, 61, 24),
                new Location(bukkitWorld, -1, 61, 24),
                new Location(bukkitWorld, 1, 61, 24),
                new Location(bukkitWorld, 4, 61, 24),
                new Location(bukkitWorld, 16, 61, 24),
                new Location(bukkitWorld, 20, 61, 24),
                new Location(bukkitWorld, 26, 61, 24),
                new Location(bukkitWorld, -21, 61, 26),
                new Location(bukkitWorld, -18, 61, 26),
                new Location(bukkitWorld, -12, 61, 26),
                new Location(bukkitWorld, -9, 61, 26),
                new Location(bukkitWorld, -6, 61, 26),
                new Location(bukkitWorld, 6, 61, 26),
                new Location(bukkitWorld, 9, 61, 26),
                new Location(bukkitWorld, 12, 61, 26),
                new Location(bukkitWorld, 18, 61, 26),
                new Location(bukkitWorld, 22, 61, 26),
                new Location(bukkitWorld, 20, 61, 27),
                new Location(bukkitWorld, 26, 61, 27),
                new Location(bukkitWorld, -27, 61, 28),
                new Location(bukkitWorld, -4, 61, 28),
                new Location(bukkitWorld, 4, 61, 28),
            ],
        },
        regions: {
            arenaStairs: new regions_1.Region(new vector3_1.Vector3(3, 67, 28, bukkitWorld.name), new vector3_1.Vector3(-3, 62, 24, bukkitWorld.name), bukkitWorld.name),
            endPortal: [
                new Location(bukkitWorld, 3, 73, 105),
                new Location(bukkitWorld, -3, 85, 126),
            ],
            endGate: [
                new Location(bukkitWorld, 2, 73, 104),
                new Location(bukkitWorld, -1, 75, 104),
            ],
        },
    };
};
