// See: https://docs.google.com/spreadsheets/d/1sBXHWGaFVnnQdjPJCrUoMBPfoOnOrarQPuqkRtcIUe4/edit#gid=285145649
const foods = [
    { type: 'COOKIE', carbs: 20, GI: 'high' },
    { type: 'COOKED_CHICKEN', carbs: 30, GI: 'low' },
    { type: 'COOKED_FISH', carbs: 25, GI: 'low' },
    { type: 'PUMPKIN_PIE', carbs: 40, GI: 'high' },
    { type: 'CAKE_SLICE', carbs: 20, GI: 'high' },
    { type: 'APPLE', carbs: 10, GI: 'high' },
    { type: 'MELON', carbs: 10, GI: 'high' },
    { type: 'CHORUS_FRUIT', carbs: 20, GI: 'high' },
    { type: 'CARROT', carbs: 15, GI: 'low' },
    { type: 'BEETROOT', carbs: 5, GI: 'low' },
    { type: 'POTATO', carbs: 5, GI: 'low' },
    { type: 'BAKED_POTATO', carbs: 25, GI: 'high' },
    { type: 'POISONOUS_POTATO', carbs: 10, GI: 'low' },
    { type: 'COOKED_BEEF', carbs: 40, GI: 'low' },
    { type: 'RAW_BEEF', carbs: 15, GI: 'low' },
    { type: 'COOKED_MUTTON', carbs: 30, GI: 'low' },
    { type: 'MUTTON', carbs: 10, GI: 'low' },
    { type: 'GRILLED_PORK', carbs: 40, GI: 'low' },
    { type: 'PORK', carbs: 15, GI: 'low' },
    { type: 'COOKED_RABBIT', carbs: 25, GI: 'low' },
    { type: 'RABBIT', carbs: 15, GI: 'low' },
    { type: 'RAW_CHICKEN', carbs: 10, GI: 'low' },
    { type: 'RAW_FISH', carbs: 10, GI: 'low' },
    { type: 'CLOWNFISH', carbs: 5, GI: 'low' },
    { type: 'PUFFERFISH', carbs: 5, GI: 'low' },
    { type: 'ROTTEN_FLESH', carbs: 20, GI: 'low' },
    { type: 'SPIDER_EYE', carbs: 10, GI: 'low' },
    { type: 'BREAD', carbs: 25, GI: 'high' },
    { type: 'BEETROOT_SOUP', carbs: 30, GI: 'low' },
    { type: 'MUSHROOM_SOUP', carbs: 30, GI: 'low' },
    { type: 'RABBIT_STEW', carbs: 50, GI: 'low' },
    { type: 'GOLDEN_APPLE', carbs: 20, GI: 'high' },
    { type: 'GOLDEN_CARROT', carbs: 30, GI: 'low' },
]

export default foods
