// See: https://docs.google.com/spreadsheets/d/1sBXHWGaFVnnQdjPJCrUoMBPfoOnOrarQPuqkRtcIUe4/edit#gid=285145649
const foods = [
    { type: 'COOKIE', label: 'Cookie', carbs: 20, GI: 'high' },
    { type: 'COOKED_CHICKEN', label: 'Crumbed Chicken', carbs: 30, GI: 'low' },
    { type: 'COOKED_COD', label: 'Battered Fish', carbs: 25, GI: 'low' },
    { type: 'PUMPKIN_PIE', label: 'Pumpkin Pie', carbs: 40, GI: 'high' },
    { type: 'CAKE_SLICE', label: 'Cake Slice', carbs: 20, GI: 'high' },
    { type: 'APPLE', label: 'Apple', carbs: 10, GI: 'high' },
    { type: 'MELON', label: 'Melon', carbs: 10, GI: 'high' },
    { type: 'CHORUS_FRUIT', label: 'Chorus Fruit', carbs: 20, GI: 'high' },
    { type: 'CARROT', label: 'Carrot', carbs: 15, GI: 'low' },
    { type: 'BEETROOT', label: 'Beetroot', carbs: 5, GI: 'low' },
    { type: 'POTATO', label: 'Potato', carbs: 5, GI: 'low' },
    { type: 'BAKED_POTATO', label: 'Baked Potato', carbs: 25, GI: 'high' },
    { type: 'POISONOUS_POTATO', label: 'Poison Potato', carbs: 10, GI: 'low' },
    { type: 'COOKED_BEEF', label: 'Honeyed Steak', carbs: 40, GI: 'low' },
    { type: 'BEEF', label: 'Gravy Steak', carbs: 15, GI: 'low' },
    { type: 'COOKED_MUTTON', label: 'Honeyed Mutton', carbs: 30, GI: 'low' },
    { type: 'MUTTON', label: 'Gravy Mutton', carbs: 10, GI: 'low' },
    {
        type: 'COOKED_PORKCHOP',
        label: 'Honeyed Porkchop',
        carbs: 40,
        GI: 'low',
    },
    { type: 'PORKCHOP', label: 'Gravy Porkchop', carbs: 15, GI: 'low' },
    { type: 'COOKED_RABBIT', label: 'Honeyed Rabbit', carbs: 25, GI: 'low' },
    { type: 'RABBIT', label: 'Gravy Rabbit', carbs: 15, GI: 'low' },
    { type: 'CHICKEN', label: 'Gravy Chicken', carbs: 10, GI: 'low' },
    { type: 'COD', label: 'Cod', carbs: 10, GI: 'low' },
    { type: 'TROPICAL_FISH', label: 'Tropical Fish', carbs: 5, GI: 'low' },
    { type: 'PUFFERFISH', label: 'Puffer Fish', carbs: 5, GI: 'low' },
    { type: 'ROTTEN_FLESH', label: 'Rotten Flesh', carbs: 20, GI: 'low' },
    { type: 'SPIDER_EYE', label: 'Spider Eye', carbs: 10, GI: 'low' },
    { type: 'BREAD', label: 'Bread', carbs: 25, GI: 'high' },
    { type: 'BEETROOT_SOUP', label: 'Beetroot Soup', carbs: 30, GI: 'low' },
    { type: 'MUSHROOM_STEW', label: 'Mushroom Stew', carbs: 30, GI: 'low' },
    { type: 'RABBIT_STEW', label: 'Rabbit and Potatoes', carbs: 50, GI: 'low' },
    { type: 'GOLDEN_APPLE', label: 'Golden Apple', carbs: 20, GI: 'high' },
    { type: 'GOLDEN_CARROT', label: 'Golden Carrot', carbs: 30, GI: 'low' },
]

export default foods
