"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// See: https://docs.google.com/spreadsheets/d/1sBXHWGaFVnnQdjPJCrUoMBPfoOnOrarQPuqkRtcIUe4/edit#gid=285145649
var foods = [
    { type: 'COOKIE', carbs: 20, GI: 'high' },
    { type: 'COOKED_CHICKEN', carbs: 30, GI: 'low' },
    { type: 'COOKED_COD', carbs: 25, GI: 'low' },
    { type: 'PUMPKIN_PIE', carbs: 40, GI: 'high' },
    { type: 'CAKE_SLICE', carbs: 20, GI: 'high' },
    { type: 'APPLE', carbs: 10, GI: 'high' },
    { type: 'MELON', carbs: 10, GI: 'high' },
    { type: 'CHORUS_FRUIT', carbs: 20, GI: 'high' },
    { type: 'CARROT', carbs: 15, GI: 'low' },
    { type: 'BEETROOT', carbs: 5, GI: 'low' },
    { type: 'POTATO', carbs: 5, GI: 'low' },
    { type: 'BAKED_POTATO', carbs: 25, GI: 'high' },
    { type: 'POISONOUS_POTATO', carbs: 10, GI: 'low' },
    { type: 'COOKED_BEEF', carbs: 40, GI: 'low' },
    { type: 'BEEF', carbs: 15, GI: 'low' },
    { type: 'COOKED_MUTTON', carbs: 30, GI: 'low' },
    { type: 'MUTTON', carbs: 10, GI: 'low' },
    { type: 'COOKED_PORKCHOP', carbs: 40, GI: 'low' },
    { type: 'PORKCHOP', carbs: 15, GI: 'low' },
    { type: 'COOKED_RABBIT', carbs: 25, GI: 'low' },
    { type: 'RABBIT', carbs: 15, GI: 'low' },
    { type: 'CHICKEN', carbs: 10, GI: 'low' },
    { type: 'COD', carbs: 10, GI: 'low' },
    { type: 'TROPICAL_FISH', carbs: 5, GI: 'low' },
    { type: 'PUFFERFISH', carbs: 5, GI: 'low' },
    { type: 'ROTTEN_FLESH', carbs: 20, GI: 'low' },
    { type: 'SPIDER_EYE', carbs: 10, GI: 'low' },
    { type: 'BREAD', carbs: 25, GI: 'high' },
    { type: 'BEETROOT_SOUP', carbs: 30, GI: 'low' },
    { type: 'MUSHROOM_STEW', carbs: 30, GI: 'low' },
    { type: 'RABBIT_STEW', carbs: 50, GI: 'low' },
    { type: 'GOLDEN_APPLE', carbs: 20, GI: 'high' },
    { type: 'GOLDEN_CARROT', carbs: 30, GI: 'low' },
];
exports.default = foods;
